### ISSUE TITLE
GitHub Page Guide - Private Repo publish

### ISSUE THREAD

**Issue by SukkaW** [hexojs/site#1140]
https://github.com/hexojs/site/blob/master/source/docs/github-pages.md

> 5. Remove everything including any hidden files **except** the `.git/` folder. Fret not, those files are still residing at the master branch.
> 6. Move the _content_ of the `public/` folder back.
> 7. Commit and push the gh-pages branch.
> ...
> 10. To navigate back to your source folder,

It is too complicated. We already have `hexo-deployer-git`, why shouldn't we just use it?

We only need to give an example config for `hexo-deployer-git`, like this:

```yaml
deploy:
  type: git
  repo: https://github.com/<your github username>/<your github username>.github.io.git
  branch: gh-pages
```
