### ISSUE TITLE
Git Section in one-command-deployment.html is incorrect

### ISSUE THREAD

**Issue by 3wweiweiwu** [hexojs/site#1934]
Current deploy section is out-of-date. When I use the command for Github, it keep giving me error: 
```
fatal: could not read Username for 'https://github.com/': No such device or address
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
```

After searching online, I use following code to successfully push my site to GitHub.

```
deploy:
  type: git
  repo:
    github:
      url: <repository url> # https://github.com/***/***.github.io.git
      branch: [branch]
      message: [message]
```
